### PR TITLE
feat: setup env with cli

### PR DESCRIPTION
**Pull request by theanupambista**
This PR introduces a bash script that allows users to configure backup options and notifications. The script prompts users to choose between GMAIL and S3_BUCKET as backup options and to specify relevant details based on their choice. It also allows users to select between Slack and Discord for backup notifications and provides the required configuration details. All configurations are saved in a .env file.

### CODE REVIEW

**Comment by isarojdahal** [comment]
Wow, great PR.
Also currently we do now support multiple notifications ; contributed by @mukezhz  on PR #13 
like `BACKUP_NOTIFICATION= SLACK, DISCORD`
or simply `BACKUP_NOTIFICATION=SLACK` will also work fine.

Besides that, I do have one thing in mind; what if , user want to update notification configuration only;
Or, Backup Destionation option only.; from CLI.
we can consider that part also.

**Comment by theanupambista** [comment]
Support for multiple notification using cli is done
And also with flag --update-notification-config notification only configuration can be done. This flag only works once the .env file is created.
--help flag will show all available flags. Currently only --update-notification-config is available.

**Comment by isarojdahal** [comment]
Great. This covers most of them.

On same idea, we can add flag for  `--update-backup-dest` also.
Also can you put some screenshots of its working too.

Thanks.

**Comment by theanupambista** [comment]
Using --help
image

Using --update-notification-config
image

**Comment by mukezhz** [comment]
@theanupambista 
how about making terminal interactive?

**Comment by theanupambista** [comment]
In the current implementation:
Option Selection: Users can select options from a menu using select, which is an interactive way to handle choices.
Input Prompts: The script uses read -p to prompt users for input, making it easy for users to provide their details.

If additional interactivity is desired, here are some enhancements we could consider:
Enhanced Prompts: We could add more descriptive prompts and guide users through each step with clearer instructions.
Validation: Implement input validation to ensure users enter correct and valid data.
Interactive Menus: Incorporate more interactive features like dynamic options based on previous inputs or error recovery steps if users make incorrect selections.

Please let me know if you have specific suggestions or examples of how you'd like the terminal interaction to be enhanced!

**Comment by mukezhz** [comment]
@theanupambista The interactive I was talking about is like this.

[inquirer](https://github.com/SBoudrias/Inquirer.js)

image

**Comment by theanupambista** [comment]
If we use nodejs for cli then we can build it using the package you mentioned above. But in current scenario, I don't have any idea to make shell such interactive.

**Comment by mukezhz** [comment]
@theanupambista oh okay

**Comment by theanupambista** [comment]
@mukezhz Setup for cli is completed. I had deleted the index.sh file as it's work is done by index.js file with command:
node index.js install

**Comment by theanupambista** [comment]
Installation and .env file process creation using cli completed
**Command to do so:**
`node index.js install or node index.js i`

**Comment by theanupambista** [comment]
**Added  two more commands:**
`node index.js update-notification-config`
`node index.js update-backup-dest`

**Review by isarojdahal — APPROVED** [review]

**Pull request merged**
