### PR TITLE
Project structure changed with extra flexibility

### PR DESCRIPTION
**Pull request by Aspasht**
- Added new config type for extra security a
- Dump files are stored on separate folder under database name
- Fixed dump file names to avoid duplication when multiple database creation occur at the same time 
- Auto remove .sql dump files after zipped 
- Updated README.md

### CODE REVIEW

**Comment by Aspasht** [comment]
I've added feature to send desired backup files through email. End user can configure config files to select which database backup to send through email.

**Review by isarojdahal — CHANGES_REQUESTED** [review]
config.ts file should be updated as below.
(so we can use same config with multiple database name).

```/* eslint-disable no-undef */
import "dotenv/config";
import { ConfigType } from "./src/types";

const dbConfig: ConfigType[] = [];

if (process.env.POSTGRES_DB_HOST || process.env.POSTGRES_DB_NAME) {
  const databaseNameList = process.env.POSTGRES_DB_NAME?.split(" ");

  if (databaseNameList && databaseNameList.length > 0) {
    databaseNameList.forEach((databaseName) => {
      dbConfig.push({
        host: process.env.POSTGRES_DB_HOST,
        db_name: process.env.POSTGRES_DB_NAME,
        user: process.env.POSTGRES_DB_USER,
        password: process.env.POSTGRES_DB_PASSWORD,
        mail_backup: false,
        type: "postgres",
      });
    });
  }
} else if (process.env.MYSQL_DB_HOST || process.env.MYSQL_DB_NAME) {
  const databaseNameList = process.env.MYSQL_DB_NAME?.split(" ");

  if (databaseNameList && databaseNameList.length > 0) {
    databaseNameList.forEach((databaseName) => {
      dbConfig.push({
        host: process.env.MYSQL_DB_HOST,
        db_name: process.env.MYSQL_DB_NAME,
        user: process.env.MYSQL_DB_USER,
        password: process.env.MYSQL_DB_PASSWORD,
        mail_backup: false,
        type: "mysql",
      });
    });
  }
}

export default dbConfig;
```

**Comment by isarojdahal** [comment]
Also , you can manage the env by creating config > env.config.ts
which will have following code 

```
import "dotenv/config";

class EnvConfiguration {
  public static MAIL_USER = process.env.MAIL_USER;
  public static MAIL_PASSWORD = process.env.MAIL_PASSWORD;
}

export default EnvConfiguration;
```

Usuage:
EnvConfiguration.MAIL_USER

**Comment by Aspasht** [comment]
Can you briefly explain why we're checking database types in the config which we're already checking in backupHelper() function which will throw error if database config type is other than postgres or mysql . For multiple database we can simply do this. 
```
const dbConfig:ConfigType[]   = [
  {
    host: process.env.POSTGRES_HOST,
    db_name: process.env.POSTGRES_NAME,
    user: process.env.POSTGRES_DB_USER,
    password: process.env.POSTGRES_PASSWORD,
    type: "postgres",
    mail_backup: true  
    port: 5432, 
    ssl: false, 
  },
  {
    host: process.env.MYSQL_HOST,
    db_name: process.env.MYSQL_NAME,
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    type: "mysql",
    mail_backup: true  
    port: 5432, 
    ssl: false, 
  },
 // more database 
];
```
I think this is better and more flexible to add support for other kinds of databases.

**Comment by Aspasht** [comment]
@isarojdahal  added env.config.ts as you suggested. I review config.ts you suggested, there's a edge case. 

## Exceptions
- What if user has multiple Postgres or multiple Mysql databases. 
- Suppose user have two postgres databases and he wants to mail only one backup.  

We can modify  and implement config.ts you suggested to meet this behaviour but this will add more complexity and also users have to set specific environment variable names that makes it less flexible. We should merge this PR.

**Comment by isarojdahal** [comment]
Yes, you are right @Aspasht , the code was repeated on dbConfig part; that same logic should be on backupHelper.
And, also we should be open for other different database type backup too.

My intention in doing loop in dbConfig was to make possible to extract multiple database name so that we can take multiple db backups of same config.
like; POSTGRES_DB_NAME="mydatabase1 mydatabase2 mydatabase3"
It was supposed to be separated by 'spaces' for multiple database backup (with same postgres config) in this case.

Whereas, for emailing, the purpose of library is for mailing  backuped db, so lets keep mailing part default true for now.

**Comment by Aspasht** [comment]
Push new commit updating mail_backup defaults to true, can disable by setting it to false. Also updated readme. We are good to go @isarojdahal .

**Pull request merged**
